DROP TABLE IF EXISTS BOOK_EMPLOYEE;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE BOOK(
  BOOK_ID INT(11) NOT NULL AUTO_INCREMENT ,
  TITLE VARCHAR(50) NOT NULL ,
  AUTHOR VARCHAR(50) NOT NULL ,
  BRIEF VARCHAR(80) ,
  PUBLISH_DATE DATE NOT NULL ,
  PRIMARY KEY (BOOK_ID)
);

CREATE TABLE EMPLOYEE(
  EMPLOYEE_ID INT(11) NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(50) NOT NULL ,
  EMAIL VARCHAR(50) NOT NULL ,
  BIRTH_DATE DATE NOT NULL ,
  PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE BOOK_EMPLOYEE(
  ID INT(11) NOT NULL AUTO_INCREMENT ,
  BOOK_ID INT(11) NOT NULL,
  EMPLOYEE_ID INT(11) NOT NULL,
  FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE,
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON DELETE CASCADE,
  PRIMARY KEY (ID)
);